title: Honor's Page

posts_dir: _posts
collections:
  posts:
    output: true

#baseurl: "http://suzannehare.git.io"
#url: "http://suzannehare.git.io"

theme: jekyll-theme-leap-day
markdown: kramdown
